name: Supabase Type Generation

on:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: supabase/setup-cli@v1

      - name: Start Supabase local development setup
        run: |
          cd apps/web
          supabase start

      - name: Verify generated types are up-to-date
        run: |
          supabase gen types typescript --local > src/types/database.types.ts
          if [ "$(git diff --ignore-space-at-eol types.ts | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build. See status below:"
            git diff
            exit 1
          fi
